# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

# Add a label to an issue based on the selected value of the Product drop down
# in the issue form

policy:
  - template: [bug-report.yml, feature-request.yml]
    section:
      - id: [product]
        label:
          - name: 'Boundary'
            keys: ['Boundary']
          - name: 'Consul'
            keys: ['Consul']
          - name: 'HCP'
            keys: ['HCP']
          - name: 'Nomad'
            keys: ['Nomad']
          - name: 'Packer'
            keys: ['Packer']
          - name: 'Sentinel'
            keys: ['Sentinel']
          - name: 'Terraform CE'
            keys: ['Terraform']
          - name: 'Vault'
            keys: ['Vault'] 
          - name: 'WAF'
            keys: ['Well-Architected Framework']
   