name: Bug Report
description: |-
  Create an issue for incorrect content or content that should be there but is not.
title: "[Content Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation bug report!
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: What documentation is this for?
      options:
        - Boundary
        - Consul
        - HCP
        - Nomad
        - Packer
        - Sentinel
        - Terraform
        - Vagrant
        - Vault
        - Well-Architected Framework
      default: 0
    validations:
      required: true
  - type: textarea
    id: which-page
    attributes:
      label: Which page?
      description: The page URL
      placeholder: https://developer.hashicorp.com/
      value: "https://developer.hashicorp.com/..."
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue?
      description: Describe the issue - what content is incorrect? 
      placeholder: Tell us what you see!
      value: "Something is not quite right with the content...
    validations:
      required: true
