# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

blank_issues_enabled: false
contact_links:
   - name: Nomad docs issue
     url: https://github.com/hashicorp/nomad/issues
     about: Create a Nomad docs issue in the Nomad repository.
 