# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

blank_issues_enabled: false
contact_links:
   - name: Consul docs issue
     url: https://github.com/hashicorp/consul/issues
     about: Create a Consul docs issue in the Consul repository.
   - name: Nomad docs issue
     url: https://github.com/hashicorp/nomad/issues
     about: Create a Nomad docs issue in the Nomad repository.
 