name: Documentation Issue
description: HashiCorp Cloud Platform, HCP Waypoint, Sentinel, Well-Architected Framework
title: "[Content Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation issue!
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: What documentation is this for?
      options:
        - HashiCorp Cloud Platform     
        - HCP CLI
        - HCP Waypoint
        - Sentinel
        - Well-Architected Framework        
        - Other product
        - No product
      default: 1
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: |-
        What content updates would you like us to do? Be specific and provide as much detail as possible.
      description: 
      placeholder: Please document how to... 
      value: "Please document how to..."
    validations:
      required: true

