name: Documentation Request
description: Request new or updated documentation.
title: "[Content Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation feature request!
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: What documentation is this for?
      options:
        - Boundary
        - Consul
        - HCP
        - Nomad
        - Packer
        - Sentinel
        - Terraform
        - Vagrant
        - Vault
        - Well-Architected Framework
      default: 6
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: |-
        What would you like us to document? Be specific and provide as much detail as possible.
      description: 
      placeholder: Please document how to... 
      value: "Please document how to..."
    validations:
      required: true

